import React, {useState , useEffect} from "react";
import { Card, Loader , FormField} from "../components";
import API_URL from "../config/api";

const RenderCards = ({data , title}) => {
    if(data?.length > 0) return data.map((post) => <Card key={post._id} {...post} />)

    return (
        <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
    )

}

const Home = () => {
    const [loading , setLoading] = useState(false);
    const [allPosts , setAllPosts] = useState(null);
    const [searchText , setSearchText] = useState("");
    const [serachedResults , setSearchedResults] = useState(null);
    const [searchTimeout , setSearchTimeout] = useState(null);
    useEffect(() => {
        const fetchPosts = async() => {
            try {
                setLoading(true);
                const response = await fetch(`${API_URL}/api/v1/post` , {
                    method: "GET",
                    headers: {
                        "Content-Type": "application/json",
                    },

                })
                const data = await response.json();
                if (!response.ok) throw new Error(data.message || "Something went wrong");
                setAllPosts(data.data);
            } catch (error) {
                console.log(error);
            } finally {
                setLoading(false);
            }
        };

        fetchPosts();
    } , []);

    const handleSearchChange = (e) => {
        e.preventDefault();
        clearTimeout(searchTimeout);
        setSearchText(e.target.value);
        setSearchTimeout(
            setTimeout(() => {
            const searchResults = allPosts.filter((post) => post.name.toLowerCase().includes(searchText.toLowerCase()) || post.prompt.toLowerCase().includes(searchText.toLowerCase()));
            setSearchedResults(searchResults);
        } , 500)
        );
        
    }
    return(
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
                <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
            </div>

            <div className="mt-16"><FormField labelName="Search Posts" type="text" name="text" placeholder="Search posts..." value={searchText} onChange={(e) => handleSearchChange(e)} /></div>

            <div className="mt-10">{loading ? (
                <div className="flex justify-center items-center">
                    <Loader />
                </div>) : (
                    <>
                        {searchText && (
                            <h2 className="font-medium text-[#666e75] text-xl mb-3">Showing results for <span className="text-[#222328]">{searchText}</span></h2>
                        )}

                        <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:gris-cols-2 grid-cols-1 gap-3">
                            {searchText ? (
                                <RenderCards data={serachedResults} title="No search results found"/>
                            ) : (
                                <RenderCards data={allPosts} title={allPosts.length > 0 ? "All posts" : "No posts yet" }/>
                            )}
                        </div>
                    </>
                )}
            </div>
        </section>
    )
}

export default Home;